version: "3"
services:
  emr-service:
    image: omrsregrepo/bahmni_092_emr:02122020
    restart: unless-stopped
    privileged: true
    ports:
      - "443:443"
      - "80:80"
      - "8000:8000"
  erp-service:
    image: omrsregrepo/bahmni_092_erp:02122020
    privileged: true
    ports:
      - "8069:8069"
    restart: unless-stopped
##waiting for ntate Mphatsi
