apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  rules:
    - host: localhost
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: emr-cluster-ip-service
              servicePort: 80
          - path: /api/?(.*)
            backend:
              serviceName: erp-cluster-ip-service
              servicePort: 8069
    - host: localhost
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: emr-cluster-ip-service
              servicePort: 80
          - path: /api/?(.*)
            backend:
              serviceName: erp-cluster-ip-service
              servicePort: 8069
